backend:
  name: git-gateway
  repo: yaminig13/gupta-hospital
  branch: master

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: /assets/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'companies'
    label: 'Companies'
    label_singular: 'Company'
    folder: 'content/companies'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'companies/{{slug}}'
    fields:
      - {
          label: 'Company Name',
          name: 'name',
          widget: 'string',
          required: true
        }
      - { label: 'Image', name: 'cover', widget: 'image', required: true, allow_multiple: false }
  - name: 'contact'
    label: 'Contact Info'
    folder: 'content/contact'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'contact/{{slug}}'
    fields:
      - {
          label: 'Whatsapp Number',
          name: 'wa_no',
          widget: 'string',
          required: true
        }
      - {
          label: 'Phone Number - Gynaec',
          name: 'ph_gy',
          widget: 'list',
          required: true,
          field: { label: 'Phone no- gynaec', name: 'ph_gy' }
        }  