backend:
  name: git-gateway
  branch: master

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'companies'
    label: 'Companies'
    label_singular: 'Company'
    folder: 'content/companies'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'companies/{{slug}}'
    fields:
      - {
          label: 'Company Name',
          name: 'name',
          widget: 'string',
          required: true
        }
      - { label: 'Image', name: 'cover', widget: 'image', required: true, allow_multiple: false }
